### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by GuLinux** [GuLinux/StarQuew#29]
To be further investigated.
Possible implementations:
   - [ ] Native browser notifications (depends on ssl certificate)
   - [ ] Play sound on server for critical events
   - [ ] Mobile react native app might use its own notification system
