### ISSUE TITLE
React-Native version

### ISSUE THREAD

**Issue by GuLinux** [GuLinux/StarQuew#59]
ios/android specific versions using React Native

Subtask:
 - [x] create skeleton native app
 - [ ] switch to `react-navigation`
 - [ ] add new component for selecting server
 - [ ] integrate existing components
